// Code generated by Kitex v0.10.3. DO NOT EDIT.

package rpc

import (
	"context"
	raft "github.com/B1NARY-GR0UP/raft/raftrpc/kitex_gen/raft"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Do(ctx context.Context, req *raft.Message, callOptions ...callopt.Option) (r *raft.DummyResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRPCClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRPCClient struct {
	*kClient
}

func (p *kRPCClient) Do(ctx context.Context, req *raft.Message, callOptions ...callopt.Option) (r *raft.DummyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Do(ctx, req)
}
