// Code generated by Kitex v0.10.3. DO NOT EDIT.

package rpc

import (
	raft "github.com/B1NARY-GR0UP/raft/raftrpc/kitex_gen/raft"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler raft.RPC, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
