// Code generated by Kitex v0.10.3. DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	raft "github.com/B1NARY-GR0UP/raft/raftrpc/kitex_gen/raft"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Do": kitex.NewMethodInfo(
		doHandler,
		newRPCDoArgs,
		newRPCDoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	rPCServiceInfo                = NewServiceInfo()
	rPCServiceInfoForClient       = NewServiceInfoForClient()
	rPCServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return rPCServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return rPCServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return rPCServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RPC"
	handlerType := (*raft.RPC)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "raft",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func doHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*raft.RPCDoArgs)
	realResult := result.(*raft.RPCDoResult)
	success, err := handler.(raft.RPC).Do(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRPCDoArgs() interface{} {
	return raft.NewRPCDoArgs()
}

func newRPCDoResult() interface{} {
	return raft.NewRPCDoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Do(ctx context.Context, req *raft.Message) (r *raft.DummyResp, err error) {
	var _args raft.RPCDoArgs
	_args.Req = req
	var _result raft.RPCDoResult
	if err = p.c.Call(ctx, "Do", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
